name:                weather-api
version:             0.1.0.0
github:              "githubuser/weather-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/weather-api#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- HTTP
- aeson
- http-client
- containers
- regex-compat
- regex-base
- mysql-simple
- servant
- servant-server
- servant-auth
- servant-auth-server
- warp
- wai
- wai-extra
- wai-middleware-static
- text
- bytestring
- jwt
- mysql-simple
- persistent
- persistent-mysql
- persistent-template
- data-default
- time
- io-streams
- mysql

library:
  source-dirs: src
  ghc-options:
    - -O2
  default-extensions:
    - DataKinds
    - DeriveDataTypeable
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - OverloadedStrings
    - RecordWildCards
    - TemplateHaskell
    - TypeFamilies
    - FlexibleInstances

executables:
  your-project-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
